// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCEimRFEwR_R47fz3o2IiVfH4Usow9EY',
    appId: '1:590601389080:web:ee04d49e917501b5416f6d',
    messagingSenderId: '590601389080',
    projectId: 'flutter-instagram-clone-92e3e',
    authDomain: 'flutter-instagram-clone-92e3e.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-92e3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffm3EITCVJOu4ZodoquOrGG_YLdCy9Tc',
    appId: '1:590601389080:android:15baeca953dd93ac416f6d',
    messagingSenderId: '590601389080',
    projectId: 'flutter-instagram-clone-92e3e',
    storageBucket: 'flutter-instagram-clone-92e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezrHlgSBOzt23BmQ1VxF0SjL1-P_IgMM',
    appId: '1:590601389080:ios:256766bedc1af307416f6d',
    messagingSenderId: '590601389080',
    projectId: 'flutter-instagram-clone-92e3e',
    storageBucket: 'flutter-instagram-clone-92e3e.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );
}
